version: '3.8'

services:
  postgres:
    image: "postgres:11-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/users/data
    ports:
      - "${POSTGRES_CUSTOM_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 3
  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
    ports:
      - "${REDIS_PUBLIC_PORT:-6379}:6379"

volumes:
  postgres-data:
  redis_data:
