###
POST https://nftdev.nnmdev.ru/auth/realms/nftplatform/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=account&username=nft-test@no.no&password=12345678

> {%
    client.global.set("token", "Bearer " + encodeURIComponent(response.body.access_token));
    client.log(encodeURIComponent((client.global.get("token"))));
%}
