spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nft-platform
    username: user
    password: password
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml

security:
  oauth2:
    client:
      access-token-uri: ${rest.security.issuer-uri}/protocol/openid-connect/token
      client-id: account
      scope: openid
      user-authorization-uri: ${rest.security.issuer-uri}/protocol/openid-connect/auth
    resource:
      id: account
      jwt:
        key-value: |-
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqX9FCU+uiDbTxWc4pY3rH34k1KTdHF9FoEUSZfr/VX+8r6KPnuJShVXj247/X68b3kl+mwrr8j89eROS4w09yU4tqEkB1/QBy7lpckFKdQlJ5OawAzVC642qcIV2o7PpJdyhAjEdAi4G5CmNGnuA0Jpq9qxeNWTse15BQ/30ATPdHccdthO97rpe15K5q2nqTDTJ6QN6PLYIBMMCMqKHSs6t6FRUvPqe8SL9Pk7z/Tptyc4FB2A7uJvoFGa7rwa9jVIC434w/2u1O2clQDNMfcvdycqvk+16fZqYAENw0oY2KhGtrOPfjoUOjdRG+77EmYGgTLi0BHX+PIZJZz3PNQIDAQAB
          -----END PUBLIC KEY-----
      token-info-uri: ${rest.security.issuer-uri}/protocol/openid-connect/token/introspect
      user-info-uri: ${rest.security.issuer-uri}/protocol/openid-connect/userinfo

rest:
  security:
    enabled: true
    issuer-uri: https://nft-platform.dcloud.tech/auth/realms/nftplatform

server:
  port: 8080