apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: user-service
  name: user-service-debug
  namespace: nftdev
spec:
  ports:
    - name: http
      port: 5005
      protocol: TCP
      targetPort: 5005
  selector:
    app.kubernetes.io/name: user-service
  sessionAffinity: None
  type: LoadBalancer