# Default values for temp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: "container.nexus.nnmdev.ru/nft-platform/user-service"
  tag: #default "SNAPSHOT"
  pullPolicy: Always

#imagePullSecrets:
#  - name: dcloudnexus
nameOverride: ""
fullnameOverride: ""

env:
  NFT_LOGGING_LOGSTASH_ENABLED: false
  NFT_LOGGING_USEJSONFORMAT: true

  NFT_STAND_BASE-URL: "https://nftdev.nnmdev.ru"
  NFT_TECH_USER_AUTH_USERNAME: "nftbackend@no.no"
  NFT_TECH_USER_AUTH_PASSWORD: "8yfz537z3yr7h99w"
  SERVER_SERVLET_CONTEXTPATH: "/user-service"
  SERVER_PORT: 8080
  TZ: "Europe/Moscow"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdev.cwol7reviywm.eu-central-1.rds.amazonaws.com/users
  SPRING_DATASOURCE_USERNAME: users
  SPRING_DATASOURCE_PASSWORD: users
  REDIS_ENABLED: true
  REDIS_ADDRESS: nftdevredis.elesif.clustercfg.memorydb.eu-central-1.amazonaws.com:6379

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

container:
  port: 8080

livenessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
  httpGet:
    path: /actuator/health
    port: 8080

readinessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 5
  httpGet:
    path: /actuator/health
    port: 8080


ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: nftdev.nnmdev.ru
      paths:
        - /user-service
      pathType: ImplementationSpecific
  tls:
    - secretName: nftdev.nnmdev.ru-tls
      hosts:
        - nftdev.nnmdev.ru


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
